[build-system]
requires = ["setuptools>=68.0"]
build-backend = "setuptools.build_meta"

[project]
name = "v80pp"
version = "0.1.0"
description = "Utility to link VRT binaries (VBINs) from user IP cores"
license = "MIT"
requires-python = ">=3.10"
dependencies = ["jinja2"]

[project.scripts]
v80pp = "v80pp.__main__:main"

[tool.setuptools.packages.find]
include = ["v80pp*"]
exclude = ["test*"]

[tool.setuptools.package-data]
"v80pp" = ["resources/**/*"]
