# Build environment for the SLASH .rpm packages, targeting Rocky Linux 9.
# Build the image from the repository root:
#     docker build -t slash-build-rocky -f scripts/Dockerfile.rocky .
# Then run a build by mounting the working tree:
#     docker run --rm -v "$PWD:/home/slash/SLASH" -w /home/slash/SLASH slash-build-rocky \
#         bash scripts/package-rpm.sh
# TODO: Add note for Vivado!

FROM rockylinux:9

RUN dnf install -y epel-release
RUN dnf config-manager --set-enabled crb
RUN dnf distro-sync -y
RUN dnf install -y git python3 python3-devel python3-jinja2 python3-pip python3-setuptools python3-wheel \
    cmake gcc gcc-c++ pkg-config ninja-build rsync systemd-rpm-macros rpm-build createrepo_c \
    cli11-devel cppzmq-devel inih-devel jsoncpp-devel libxml2-devel systemd-devel zeromq-devel \
    zlib-devel 

RUN useradd -m -U -u 50102781 slash
USER slash

WORKDIR /home/slash
