name: Push PR to Gitlab CI/CD
on:
  pull_request_review:
    types: [edited, submitted]
  
jobs:
  Push-PR:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: echo "Hello World!"
